### ISSUE TITLE
Can you make the notification center less opaque + the notification cards natively dark?

### ISSUE THREAD

**Issue by sidpagariya** [w0lfschild/darkNC#1]
So, I saw that in your code, you manually set the black color with an alpha level... is there a way to get a 100% vibrant dark color by preserving the transparency and vibrancy of the original notification center?
Here's the original:
<img width="344" alt="screen shot 2017-03-22 at 5 49 22 am" src="https://cloud.githubusercontent.com/assets/10685754/24193072/5fa0fc44-0ec7-11e7-8faa-6b87592b34d0.png">
Here's the one with alpha of 0.9 (I modified the code and built the bundle again with Xcode):
<img width="345" alt="screen shot 2017-03-22 at 5 47 22 am" src="https://cloud.githubusercontent.com/assets/10685754/24193089/6a4695e6-0ec7-11e7-8aae-d11764d5326f.png">
Here's the one with alpha of 0.7 (Modified alpha level of the black color once more):
<img width="342" alt="screen shot 2017-03-22 at 5 51 47 am" src="https://cloud.githubusercontent.com/assets/10685754/24193129/9019ca18-0ec7-11e7-822e-7be06a2dcf2a.png">

The way I was trying to ask was something like this:
[It seems like a bug but the dev of the Battery Health App hasn't fixed it]
**On white notification center:**
<img width="338" alt="screen shot 2017-03-22 at 6 11 51 am" src="https://cloud.githubusercontent.com/assets/10685754/24193174/b3ad4694-0ec7-11e7-843b-da4bc346e82a.png">
**On darkNC (Alpha = 0.7):**
<img width="337" alt="screen shot 2017-03-22 at 6 11 10 am" src="https://cloud.githubusercontent.com/assets/10685754/24193189/c13b9e78-0ec7-11e7-9533-8d36e75b9a56.png">

Perhaps we could implement the notification center with a native dark color (kinda like the dock...) with alpha  = 0 and just a dark vibrancy...? (Like the bug as shown above?)

I found that we could set the appearance of a view like so:
`window.appearance = NSAppearance(named: NSAppearanceNameVibrantDark)`
Could you possibly do something like this?

(P.S. I saw that after downloading the https://github.com/SamRothCA/Today-Scripts repo, and then opening the Today View xib file in the designer in Xcode, Xcode has a Vibrancy Dark Option for the window!

Thanks!
Sid.

**Comment by w0lfschild** [comment]
The blur in the new notification center is a custom NSVisualEffectView. It unfortunately wont allow it's  appearance to be set. 

I have figured out how to use a default NSVisualEffectView with NSAppearanceNameVibrantDark and use that instead though so it matches the dock and menubar better.

**Comment by w0lfschild** [comment]
Pushed some changes to this repo.

**Comment by sidpagariya** [comment]
Sweet! Thanks so much! I will check it out!

**Comment by sidpagariya** [comment]
Actually, closing this since the NC indeed looks great now!
