### ISSUE TITLE
The background colors doesn't change

### ISSUE THREAD

**Issue by doureyd** [w0lfschild/darkNC#2]
Hi, first thx for your work!
I'm under macOS 10.12.4 I tried both 1.0 and 1.1.2 version but I'm facing the same issue:
 - the font is correctly set to white however the background is still grey

![](http://i.imgur.com/IXdcRUz.png)

**Comment by w0lfschild** [comment]
It looks like that happens if you have reduce transparency on.

**Comment by doureyd** [comment]
Thanks that was it!

**Comment by w0lfschild** [comment]
I would still consider this a bug. I'll look into it at some point.
