### ISSUE TITLE
Seems to be incompatible with the latest MacOS X Sierra Security Update

### ISSUE THREAD

**Issue by itsTyrion** [w0lfschild/darkNC#3]
![image](https://user-images.githubusercontent.com/17730120/34383910-f09584d0-eb18-11e7-96d9-3559f43f5e46.png)

After downloading the latest security patch from the Mac App Store, the tweak seems to be incompatible.  The nVidia driver also needed an update, so they seem to have changed someting :/ -.-

**Comment by w0lfschild** [comment]
Working fine here:

<img width="1680" alt="screen shot 2018-03-25 at 4 12 42 pm" src="https://user-images.githubusercontent.com/1920148/37881102-68b9ea5a-3047-11e8-92ca-a2d1f4b33c1f.png">

**Comment by itsTyrion** [comment]
dunno. maybe working **again** I'll have a look later(currently on windows)

**Comment by thatJARED** [comment]
I seem to be having the same problem, following the steps given in the Readme just turns out to this. :/ It must only be compatible with High Sierra.

![screen shot 2018-06-30 at 10 05 59 pm](https://user-images.githubusercontent.com/17349406/42125023-08037688-7cb2-11e8-98c7-fe09e6641f06.png)

**Comment by w0lfschild** [comment]
Might have to do with reduced transparency setting?
